version: '3.8'

services:
    db:
        image: postgres:16
        container_name: postgres
        restart: always
        shm_size: 512mb
        environment:
            POSTGRES_USER: freqtrade
            POSTGRES_PASSWORD: fr3qtrade
            POSTGRES_DB: freqtrade_db
            DATABASES: freqtrade_binance_x5_spot_db,freqtrade_bitget_x5_spot_db,freqtrade_gateio_x5_spot_db
        volumes:
            - /home/holu/docker-volumes/postgres-data:/var/lib/postgresql/data
            - ./freqtrade_configs/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        networks:
            - freqtrade-net
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'freqtrade']
            interval: 30s
            timeout: 10s
            retries: 5
        command: bash -c "
            docker-entrypoint.sh postgres &
            /docker-entrypoint-initdb.d/init-db.sh &&
            wait
            "

    # WATCHDOG: Check Freqtrade health bots and restart if they are not running
    watchdog:
        build:
            context: .
            dockerfile: Dockerfile.watchdog
        container_name: freqtrade_watchdog
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./freqtrade_configs/scripts:/scripts:ro
        networks:
            - freqtrade-net
        environment:
            - WATCHDOG_INTERVAL=60
        depends_on:
            - BinanceX5Spot
            - BitgetX5Spot

    BinanceX5Spot:
        build:
            context: .
            dockerfile: Dockerfile.custom
        image: freqtradeorg/freqtrade:stable
        container_name: BinanceX5Spot
        restart: always
        volumes:
            - ./user_data:/freqtrade/user_data
            - ./freqtrade_configs/scripts:/scripts:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - WAITFORIT_SERVICE=db
            - WAITFORIT_PORT=5432
            - FREQTRADE__API_SERVER__USERNAME=${BINANCEX5SPOT_API_SERVER__USERNAME}
            - FREQTRADE__API_SERVER__PASSWORD=${BINANCEX5SPOT_API_SERVER__PASSWORD}
            - FREQTRADE__API_SERVER__JWT_SECRET_TOKEN=${BINANCEX5SPOT_API_SERVER__JWT_SECRET_TOKEN}
            - FREQTRADE__API_SERVER__WS_TOKEN=${BINANCEX5SPOT_API_SERVER__WS_TOKEN}
            - FREQTRADE__TELEGRAM__ENABLED=${BINANCEX5SPOT_TELEGRAM__ENABLED}
            - FREQTRADE__TELEGRAM__TOKEN=${BINANCEX5SPOT_TELEGRAM__TOKEN}
            - FREQTRADE__TELEGRAM__CHAT_ID=${BINANCEX5SPOT_TELEGRAM__CHAT_ID}
            - FREQTRADE__EXCHANGE__KEY=${BINANCEX5SPOT_EXCHANGE__KEY}
            - FREQTRADE__EXCHANGE__SECRET=${BINANCEX5SPOT_EXCHANGE__SECRET}
            - FREQTRADE__EXCHANGE__ENABLE_WS=${BINANCEX5SPOT_EXCHANGE__ENABLE_WS}
        ports:
            - '127.0.0.1:8081:8080'
        networks:
            - freqtrade-net
        depends_on:
            - db
        command: >
            trade
            --logfile /freqtrade/user_data/logs/BinanceX5Spot.log
            --db-url postgresql+psycopg2://freqtrade:fr3qtrade@db:5432/freqtrade_binance_x5_spot_db
            --config /freqtrade/user_data/configs/BinanceX5Spot.json
            --strategy NostalgiaForInfinityX5

    BitgetX5Spot:
        build:
            context: .
            dockerfile: Dockerfile.custom
        image: freqtradeorg/freqtrade:stable
        container_name: BitgetX5Spot
        restart: always
        volumes:
            - ./user_data:/freqtrade/user_data
            - ./freqtrade_configs/scripts:/scripts:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - WAITFORIT_SERVICE=db
            - WAITFORIT_PORT=5432
            - FREQTRADE__API_SERVER__USERNAME=${BITGETX5SPOT_API_SERVER__USERNAME}
            - FREQTRADE__API_SERVER__PASSWORD=${BITGETX5SPOT_API_SERVER__PASSWORD}
            - FREQTRADE__API_SERVER__JWT_SECRET_TOKEN=${BITGETX5SPOT_API_SERVER__JWT_SECRET_TOKEN}
            - FREQTRADE__API_SERVER__WS_TOKEN=${BITGETX5SPOT_API_SERVER__WS_TOKEN}
            - FREQTRADE__TELEGRAM__ENABLED=${BITGETX5SPOT_TELEGRAM__ENABLED}
            - FREQTRADE__TELEGRAM__TOKEN=${BITGETX5SPOT_TELEGRAM__TOKEN}
            - FREQTRADE__TELEGRAM__CHAT_ID=${BITGETX5SPOT_TELEGRAM__CHAT_ID}
            - FREQTRADE__EXCHANGE__KEY=${BITGETX5SPOT_EXCHANGE__KEY}
            - FREQTRADE__EXCHANGE__SECRET=${BITGETX5SPOT_EXCHANGE__SECRET}
            - FREQTRADE__EXCHANGE__PASSWORD=${BITGETX5SPOT_EXCHANGE__PASSPHRASE}
        ports:
            - '127.0.0.1:8082:8080'
        networks:
            - freqtrade-net
        depends_on:
            - db
        command: >
            trade
            --logfile /freqtrade/user_data/logs/BitgetX5Spot.log
            --db-url postgresql+psycopg2://freqtrade:fr3qtrade@db:5432/freqtrade_bitget_x5_spot_db
            --config /freqtrade/user_data/configs/BitgetX5Spot.json
            --strategy NostalgiaForInfinityX5

    GateioX5Spot:
        build:
            context: .
            dockerfile: Dockerfile.custom
        image: freqtradeorg/freqtrade:stable
        container_name: GateioX5Spot
        restart: always
        volumes:
            - ./user_data:/freqtrade/user_data
            - ./freqtrade_configs/scripts:/scripts:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - WAITFORIT_SERVICE=db
            - WAITFORIT_PORT=5432
            - FREQTRADE__API_SERVER__USERNAME=${GATEIOX5SPOT_API_SERVER__USERNAME}
            - FREQTRADE__API_SERVER__PASSWORD=${GATEIOX5SPOT_API_SERVER__PASSWORD}
            - FREQTRADE__API_SERVER__JWT_SECRET_TOKEN=${GATEIOX5SPOT_API_SERVER__JWT_SECRET_TOKEN}
            - FREQTRADE__API_SERVER__WS_TOKEN=${GATEIOX5SPOT_API_SERVER__WS_TOKEN}
            - FREQTRADE__TELEGRAM__ENABLED=${GATEIOX5SPOT_TELEGRAM__ENABLED}
            - FREQTRADE__TELEGRAM__TOKEN=${GATEIOX5SPOT_TELEGRAM__TOKEN}
            - FREQTRADE__TELEGRAM__CHAT_ID=${GATEIOX5SPOT_TELEGRAM__CHAT_ID}
        ports:
            - '127.0.0.1:8083:8080'
        networks:
            - freqtrade-net
        depends_on:
            - db
        command: >
            trade
            --logfile /freqtrade/user_data/logs/GateioX5Spot.log
            --db-url postgresql+psycopg2://freqtrade:fr3qtrade@db:5432/freqtrade_gateio_x5_spot_db
            --config /freqtrade/user_data/configs/GateioX5Spot.json
            --strategy NostalgiaForInfinityX5

networks:
    freqtrade-net:
        name: freqtrade-net
