FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y docker.io bash && \
    apt-get clean

COPY ./freqtrade_configs/scripts/watchdog.sh /watchdog.sh
RUN chmod +x /watchdog.sh

CMD ["bash", "/watchdog.sh"]