version: '3.8'

services:
    db:
        image: postgres:16
        container_name: postgres
        restart: always
        shm_size: 256mb
        environment:
            POSTGRES_USER: freqtrade
            POSTGRES_PASSWORD: fr3qtrade
            POSTGRES_DB: freqtrade_db
            DATABASES: freqtrade_binance_x5_spot_db,freqtrade_bitget_x5_spot_db
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./freqtrade_configs/scripts:/scripts:ro
        networks:
            - freqtrade-net
        command:
            [
                'bash',
                '-c',
                'docker-entrypoint.sh postgres & /scripts/init-db.sh',
            ]
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'freqtrade']
            interval: 30s
            timeout: 10s
            retries: 5

    BinanceX5Spot:
        build:
            context: .
            dockerfile: Dockerfile.custom
        image: freqtradeorg/freqtrade:stable
        container_name: BinanceX5Spot
        restart: always
        volumes:
            - ./user_data:/freqtrade/user_data
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - '127.0.0.1:8081:8080'
        networks:
            - freqtrade-net
        depends_on:
            - db
        command: >
            trade
            --logfile /freqtrade/user_data/logs/BinanceX5Spot.log
            --db-url postgresql+psycopg2://freqtrade:fr3qtrade@db:5432/freqtrade_binance_x5_spot_db
            --config /freqtrade/user_data/configs/BinanceX5Spot.json
            --strategy NostalgiaForInfinityX5

    BitgetX5Spot:
        build:
            context: .
            dockerfile: Dockerfile.custom
        image: freqtradeorg/freqtrade:stable
        container_name: BitgetX5Spot
        restart: always
        volumes:
            - ./user_data:/freqtrade/user_data
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - '127.0.0.1:8082:8080'
        networks:
            - freqtrade-net
        depends_on:
            - db
        command: >
            trade
            --logfile /freqtrade/user_data/logs/BitgetX5Spot.log
            --db-url postgresql+psycopg2://freqtrade:fr3qtrade@db:5432/freqtrade_bitget_x5_spot_db
            --config /freqtrade/user_data/configs/BitgetX5Spot.json
            --strategy NostalgiaForInfinityX5

networks:
    freqtrade-net:
        name: freqtrade-net
